### PR TITLE
Fix failing facade tests

### PR DESCRIPTION
**Pull request by Shiro-Raven**

### CODE REVIEW

**Review by astralcai — APPROVED** [review]

**Review by mudit2812 — APPROVED** [review]

**Comment by astralcai** [comment]
[sc-72151]

**Comment by mlxd** [comment]
Hey all, is a force-merge required here? Any reason the codecov action isn't reporting?

**Comment by astralcai** [comment]
> Hey all, is a force-merge required here? Any reason the codecov action isn't reporting?

@mlxd I don't know why codecov isn't reporting here but a force merge should be safe. Would you be able to do it?

**Comment by mudit2812** [comment]
@mlxd the upload to codecov step for all the tests jobs is failing (see [here](https://github.com/PennyLaneAI/pennylane-aqt/actions/runs/10567476643/job/29276505646?pr=57#step:8:32))

**Pull request merged**
